services:
  - type: web
    name: ai-blogger-scheduler
    env: node
    plan: free
    rootDir: ai-talks-backend
    buildCommand: npm install
    startCommand: node scheduler.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_BASE_URL
        value: https://openrouter.ai/api/v1/chat/completions
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: HUGGINGFACE_BASE_URL
        value: https://api-inference.huggingface.co/models
      - key: ADMIN_KEY
        sync: false
